//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendance
    {
        public int Id { get; set; }
        public string MatricNo { get; set; }
        public string Val { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string TodayDate { get; set; }
    }
}
