//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emp
    {
        public int Id { get; set; }
        public string emp_name { get; set; }
        public string emp_age { get; set; }
        public string emp_cell { get; set; }
        public string emp_desig { get; set; }
        public string emp_salary { get; set; }
        public byte[] emp_finger { get; set; }
    }
}
